# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

parallel_fedgg <- function(S, genoM2, genoN2, genoS2, XXVX_invXVM, XXVX_invXVN, XXVX_invXVS, V, varRatio_null, N_m, N_n, N_s) {
    .Call('_FedMEGA_parallel_fedgg', PACKAGE = 'FedMEGA', S, genoM2, genoN2, genoS2, XXVX_invXVM, XXVX_invXVN, XXVX_invXVS, V, varRatio_null, N_m, N_n, N_s)
}

G_G <- function(XXVX_inv, XV) {
    .Call('_FedMEGA_G_G', PACKAGE = 'FedMEGA', XXVX_inv, XV)
}

invsig <- function(wVec, tauVec) {
    .Call('_FedMEGA_invsig', PACKAGE = 'FedMEGA', wVec, tauVec)
}

server <- function(invsig, sigmaiX, xsigmaix, sigmaiY, Yvec, wVec, tauVec) {
    .Call('_FedMEGA_server', PACKAGE = 'FedMEGA', invsig, sigmaiX, xsigmaix, sigmaiY, Yvec, wVec, tauVec)
}

server_q <- function(invsig, sigmaiX, xsigmaix, sigmaiY, Yvec, wVec, tauVec) {
    .Call('_FedMEGA_server_q', PACKAGE = 'FedMEGA', invsig, sigmaiX, xsigmaix, sigmaiY, Yvec, wVec, tauVec)
}

suofitglmm <- function(tauVec, score, AI, tol) {
    .Call('_FedMEGA_suofitglmm', PACKAGE = 'FedMEGA', tauVec, score, AI, tol)
}

suofitglmm_q <- function(tauVec, score, AI, tol) {
    .Call('_FedMEGA_suofitglmm_q', PACKAGE = 'FedMEGA', tauVec, score, AI, tol)
}

suogetcoeff <- function(wVec, tauVec, Yvec, Xmat) {
    .Call('_FedMEGA_suogetcoeff', PACKAGE = 'FedMEGA', wVec, tauVec, Yvec, Xmat)
}

suogetcoeff_q <- function(wVec, tauVec, Yvec, Xmat) {
    .Call('_FedMEGA_suogetcoeff_q', PACKAGE = 'FedMEGA', wVec, tauVec, Yvec, Xmat)
}

suoscore <- function(genoN, genoM, genoS, PGenoN, PGenoM, PGenoS) {
    .Call('_FedMEGA_suoscore', PACKAGE = 'FedMEGA', genoN, genoM, genoS, PGenoN, PGenoM, PGenoS)
}

wensigmaiX <- function(invsig, Xmat) {
    .Call('_FedMEGA_wensigmaiX', PACKAGE = 'FedMEGA', invsig, Xmat)
}

wensigmaiY <- function(invsig, Yvec) {
    .Call('_FedMEGA_wensigmaiY', PACKAGE = 'FedMEGA', invsig, Yvec)
}

getxsigmaix <- function(Xmat, sigmaiX) {
    .Call('_FedMEGA_getxsigmaix', PACKAGE = 'FedMEGA', Xmat, sigmaiX)
}


