// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// parallel_fedgg
arma::vec parallel_fedgg(const int& S, const arma::mat& genoM2, const arma::mat& genoN2, const arma::mat& genoS2, const arma::mat& XXVX_invXVM, const arma::mat& XXVX_invXVN, const arma::mat& XXVX_invXVS, const arma::vec& V, const arma::vec& varRatio_null, const int N_m, const int N_n, const int N_s);
RcppExport SEXP _FedMEGA_parallel_fedgg(SEXP SSEXP, SEXP genoM2SEXP, SEXP genoN2SEXP, SEXP genoS2SEXP, SEXP XXVX_invXVMSEXP, SEXP XXVX_invXVNSEXP, SEXP XXVX_invXVSSEXP, SEXP VSEXP, SEXP varRatio_nullSEXP, SEXP N_mSEXP, SEXP N_nSEXP, SEXP N_sSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int& >::type S(SSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type genoM2(genoM2SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type genoN2(genoN2SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type genoS2(genoS2SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type XXVX_invXVM(XXVX_invXVMSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type XXVX_invXVN(XXVX_invXVNSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type XXVX_invXVS(XXVX_invXVSSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type V(VSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type varRatio_null(varRatio_nullSEXP);
    Rcpp::traits::input_parameter< const int >::type N_m(N_mSEXP);
    Rcpp::traits::input_parameter< const int >::type N_n(N_nSEXP);
    Rcpp::traits::input_parameter< const int >::type N_s(N_sSEXP);
    rcpp_result_gen = Rcpp::wrap(parallel_fedgg(S, genoM2, genoN2, genoS2, XXVX_invXVM, XXVX_invXVN, XXVX_invXVS, V, varRatio_null, N_m, N_n, N_s));
    return rcpp_result_gen;
END_RCPP
}
// G_G
Rcpp::List G_G(arma::fmat& XXVX_inv, arma::fmat& XV);
RcppExport SEXP _FedMEGA_G_G(SEXP XXVX_invSEXP, SEXP XVSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::fmat& >::type XXVX_inv(XXVX_invSEXP);
    Rcpp::traits::input_parameter< arma::fmat& >::type XV(XVSEXP);
    rcpp_result_gen = Rcpp::wrap(G_G(XXVX_inv, XV));
    return rcpp_result_gen;
END_RCPP
}
// invsig
arma::mat invsig(arma::fvec& wVec, arma::fvec& tauVec);
RcppExport SEXP _FedMEGA_invsig(SEXP wVecSEXP, SEXP tauVecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::fvec& >::type wVec(wVecSEXP);
    Rcpp::traits::input_parameter< arma::fvec& >::type tauVec(tauVecSEXP);
    rcpp_result_gen = Rcpp::wrap(invsig(wVec, tauVec));
    return rcpp_result_gen;
END_RCPP
}
// server
Rcpp::List server(arma::mat& invsig, const arma::mat& sigmaiX, const arma::mat& xsigmaix, const arma::mat& sigmaiY, arma::fvec& Yvec, arma::fvec& wVec, arma::fvec& tauVec);
RcppExport SEXP _FedMEGA_server(SEXP invsigSEXP, SEXP sigmaiXSEXP, SEXP xsigmaixSEXP, SEXP sigmaiYSEXP, SEXP YvecSEXP, SEXP wVecSEXP, SEXP tauVecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type invsig(invsigSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type sigmaiX(sigmaiXSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type xsigmaix(xsigmaixSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type sigmaiY(sigmaiYSEXP);
    Rcpp::traits::input_parameter< arma::fvec& >::type Yvec(YvecSEXP);
    Rcpp::traits::input_parameter< arma::fvec& >::type wVec(wVecSEXP);
    Rcpp::traits::input_parameter< arma::fvec& >::type tauVec(tauVecSEXP);
    rcpp_result_gen = Rcpp::wrap(server(invsig, sigmaiX, xsigmaix, sigmaiY, Yvec, wVec, tauVec));
    return rcpp_result_gen;
END_RCPP
}
// server_q
Rcpp::List server_q(arma::mat& invsig, const arma::mat& sigmaiX, const arma::mat& xsigmaix, const arma::mat& sigmaiY, arma::fvec& Yvec, arma::fvec& wVec, arma::fvec& tauVec);
RcppExport SEXP _FedMEGA_server_q(SEXP invsigSEXP, SEXP sigmaiXSEXP, SEXP xsigmaixSEXP, SEXP sigmaiYSEXP, SEXP YvecSEXP, SEXP wVecSEXP, SEXP tauVecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type invsig(invsigSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type sigmaiX(sigmaiXSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type xsigmaix(xsigmaixSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type sigmaiY(sigmaiYSEXP);
    Rcpp::traits::input_parameter< arma::fvec& >::type Yvec(YvecSEXP);
    Rcpp::traits::input_parameter< arma::fvec& >::type wVec(wVecSEXP);
    Rcpp::traits::input_parameter< arma::fvec& >::type tauVec(tauVecSEXP);
    rcpp_result_gen = Rcpp::wrap(server_q(invsig, sigmaiX, xsigmaix, sigmaiY, Yvec, wVec, tauVec));
    return rcpp_result_gen;
END_RCPP
}
// suofitglmm
Rcpp::List suofitglmm(arma::fvec& tauVec, float score, float AI, float tol);
RcppExport SEXP _FedMEGA_suofitglmm(SEXP tauVecSEXP, SEXP scoreSEXP, SEXP AISEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::fvec& >::type tauVec(tauVecSEXP);
    Rcpp::traits::input_parameter< float >::type score(scoreSEXP);
    Rcpp::traits::input_parameter< float >::type AI(AISEXP);
    Rcpp::traits::input_parameter< float >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(suofitglmm(tauVec, score, AI, tol));
    return rcpp_result_gen;
END_RCPP
}
// suofitglmm_q
Rcpp::List suofitglmm_q(arma::fvec& tauVec, arma::fvec& score, arma::fmat& AI, float tol);
RcppExport SEXP _FedMEGA_suofitglmm_q(SEXP tauVecSEXP, SEXP scoreSEXP, SEXP AISEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::fvec& >::type tauVec(tauVecSEXP);
    Rcpp::traits::input_parameter< arma::fvec& >::type score(scoreSEXP);
    Rcpp::traits::input_parameter< arma::fmat& >::type AI(AISEXP);
    Rcpp::traits::input_parameter< float >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(suofitglmm_q(tauVec, score, AI, tol));
    return rcpp_result_gen;
END_RCPP
}
// suogetcoeff
Rcpp::List suogetcoeff(arma::fvec& wVec, arma::fvec& tauVec, arma::fvec& Yvec, const arma::mat& Xmat);
RcppExport SEXP _FedMEGA_suogetcoeff(SEXP wVecSEXP, SEXP tauVecSEXP, SEXP YvecSEXP, SEXP XmatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::fvec& >::type wVec(wVecSEXP);
    Rcpp::traits::input_parameter< arma::fvec& >::type tauVec(tauVecSEXP);
    Rcpp::traits::input_parameter< arma::fvec& >::type Yvec(YvecSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Xmat(XmatSEXP);
    rcpp_result_gen = Rcpp::wrap(suogetcoeff(wVec, tauVec, Yvec, Xmat));
    return rcpp_result_gen;
END_RCPP
}
// suogetcoeff_q
Rcpp::List suogetcoeff_q(arma::fvec& wVec, arma::fvec& tauVec, arma::fvec& Yvec, const arma::mat& Xmat);
RcppExport SEXP _FedMEGA_suogetcoeff_q(SEXP wVecSEXP, SEXP tauVecSEXP, SEXP YvecSEXP, SEXP XmatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::fvec& >::type wVec(wVecSEXP);
    Rcpp::traits::input_parameter< arma::fvec& >::type tauVec(tauVecSEXP);
    Rcpp::traits::input_parameter< arma::fvec& >::type Yvec(YvecSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Xmat(XmatSEXP);
    rcpp_result_gen = Rcpp::wrap(suogetcoeff_q(wVec, tauVec, Yvec, Xmat));
    return rcpp_result_gen;
END_RCPP
}
// suoscore
arma::fmat suoscore(arma::fmat& genoN, arma::fmat& genoM, arma::fmat& genoS, arma::fmat& PGenoN, arma::fmat& PGenoM, arma::fmat& PGenoS);
RcppExport SEXP _FedMEGA_suoscore(SEXP genoNSEXP, SEXP genoMSEXP, SEXP genoSSEXP, SEXP PGenoNSEXP, SEXP PGenoMSEXP, SEXP PGenoSSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::fmat& >::type genoN(genoNSEXP);
    Rcpp::traits::input_parameter< arma::fmat& >::type genoM(genoMSEXP);
    Rcpp::traits::input_parameter< arma::fmat& >::type genoS(genoSSEXP);
    Rcpp::traits::input_parameter< arma::fmat& >::type PGenoN(PGenoNSEXP);
    Rcpp::traits::input_parameter< arma::fmat& >::type PGenoM(PGenoMSEXP);
    Rcpp::traits::input_parameter< arma::fmat& >::type PGenoS(PGenoSSEXP);
    rcpp_result_gen = Rcpp::wrap(suoscore(genoN, genoM, genoS, PGenoN, PGenoM, PGenoS));
    return rcpp_result_gen;
END_RCPP
}
// wensigmaiX
arma::fmat wensigmaiX(arma::fmat& invsig, arma::fmat& Xmat);
RcppExport SEXP _FedMEGA_wensigmaiX(SEXP invsigSEXP, SEXP XmatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::fmat& >::type invsig(invsigSEXP);
    Rcpp::traits::input_parameter< arma::fmat& >::type Xmat(XmatSEXP);
    rcpp_result_gen = Rcpp::wrap(wensigmaiX(invsig, Xmat));
    return rcpp_result_gen;
END_RCPP
}
// wensigmaiY
arma::fvec wensigmaiY(arma::fmat& invsig, arma::fvec& Yvec);
RcppExport SEXP _FedMEGA_wensigmaiY(SEXP invsigSEXP, SEXP YvecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::fmat& >::type invsig(invsigSEXP);
    Rcpp::traits::input_parameter< arma::fvec& >::type Yvec(YvecSEXP);
    rcpp_result_gen = Rcpp::wrap(wensigmaiY(invsig, Yvec));
    return rcpp_result_gen;
END_RCPP
}
// getxsigmaix
arma::fmat getxsigmaix(const arma::fmat& Xmat, const arma::fmat& sigmaiX);
RcppExport SEXP _FedMEGA_getxsigmaix(SEXP XmatSEXP, SEXP sigmaiXSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::fmat& >::type Xmat(XmatSEXP);
    Rcpp::traits::input_parameter< const arma::fmat& >::type sigmaiX(sigmaiXSEXP);
    rcpp_result_gen = Rcpp::wrap(getxsigmaix(Xmat, sigmaiX));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_FedMEGA_parallel_fedgg", (DL_FUNC) &_FedMEGA_parallel_fedgg, 12},
    {"_FedMEGA_G_G", (DL_FUNC) &_FedMEGA_G_G, 2},
    {"_FedMEGA_invsig", (DL_FUNC) &_FedMEGA_invsig, 2},
    {"_FedMEGA_server", (DL_FUNC) &_FedMEGA_server, 7},
    {"_FedMEGA_server_q", (DL_FUNC) &_FedMEGA_server_q, 7},
    {"_FedMEGA_suofitglmm", (DL_FUNC) &_FedMEGA_suofitglmm, 4},
    {"_FedMEGA_suofitglmm_q", (DL_FUNC) &_FedMEGA_suofitglmm_q, 4},
    {"_FedMEGA_suogetcoeff", (DL_FUNC) &_FedMEGA_suogetcoeff, 4},
    {"_FedMEGA_suogetcoeff_q", (DL_FUNC) &_FedMEGA_suogetcoeff_q, 4},
    {"_FedMEGA_suoscore", (DL_FUNC) &_FedMEGA_suoscore, 6},
    {"_FedMEGA_wensigmaiX", (DL_FUNC) &_FedMEGA_wensigmaiX, 2},
    {"_FedMEGA_wensigmaiY", (DL_FUNC) &_FedMEGA_wensigmaiY, 2},
    {"_FedMEGA_getxsigmaix", (DL_FUNC) &_FedMEGA_getxsigmaix, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_FedMEGA(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}

